language: node_js
node_js:
  - stable

branches:
  only:
    - master
  except:
    - gh-pages

before_script:
  - npm install -g @angular/cli

script:
  - echo "Building for PROD"
  - ng build --prod --base-href=/binit/

after_success:
  - echo "Build SUCCESS!"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local_dir: dist # Only copy the /dist contents

after_deploy:
  - echo "Deployed to GH Pages!!"
